# Can override the default connection name with an environment variable as follows
#export SNOWFLAKE_DEFAULT_CONNECTION_NAME="default"

[default]
account = "hcb48009"
user = "KBOROLE2002"
password = "FGbtUgs9dHes3Y6"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "HOL_DB"
schema = "ANALYTICS"